[build]
    command = "npm run build:prod"
    publish = "dist"
    functions = "lambda"

[dev]
    command = "npm run serve"
    port = 8888
    targetPort = 8080
    framework = "#custom"

[[redirects]]
    from = "/notes/*"
    to = "/.netlify/functions/notes"
    status = 200
    force = true

[template.environment]
    PG_URI = "postgres://yjzkrhropgqocm:f7adfbdf70ec344f0d7fc100b7dd000dbf6c75789ea74e573506ff1761bab752@ec2-52-205-61-60.compute-1.amazonaws.com:5432/d46tqa27cdv5aa"